repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: Run go fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false

  - repo: local
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        entry: golangci-lint run --fast
        language: system
        types: [go]
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-imports
        name: Run goimports
        entry: goimports -w .
        language: system
        types: [go]

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: Run go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: go-test
        name: Run Go Tests
        entry: go test ./...
        language: system
        pass_filenames: false
